-- Initial schema: the original take-home submission's model, before the propose/vote/confirm
-- refactor (see spec-review.md and design-decisions-v2.md). A Meeting directly aggregates Slots
-- via a single nullable FK on slot — no participants, no voting, no meeting time window yet.
-- Reconstructed from the entity mapping as of commit a90cb8e (the commit before the v2 domain
-- rewrite), not invented — see design-decisions-v4.md for why this migration exists at all
-- despite the app having used Hibernate's ddl-auto until now.

create table app_user (
    id    bigint generated by default as identity primary key,
    name  varchar(255),
    email varchar(255)
);

create table calendar (
    id       bigint generated by default as identity primary key,
    owner_id bigint not null unique references app_user (id)
);

create table meeting (
    id          bigint generated by default as identity primary key,
    title       varchar(255),
    description varchar(255)
);

create table slot (
    id          bigint generated by default as identity primary key,
    calendar_id bigint not null references calendar (id),
    meeting_id  bigint references meeting (id),
    start_time  timestamptz,
    end_time    timestamptz,
    status      varchar(255),
    version     bigint
);

create index idx_slot_calendar_start on slot (calendar_id, start_time);
