-- Propose/vote/confirm meeting model (see design-decisions-v2.md). A Meeting stops aggregating
-- slots via a single nullable FK on slot; participants and their votes become first-class, and a
-- slot can belong to several PROPOSED meetings at once via a join table (at most one CONFIRMED
-- one, enforced in code by MeetingService, not a DB constraint — see CLAUDE.md).
--
-- No backfill step for existing rows: this app was never deployed with real production data
-- before this refactor, so there's nothing to migrate forward. A real deployment with existing
-- meetings would need one here (e.g. defaulting status to CONFIRMED, start/end times to a
-- placeholder or a required manual pass) before these columns could be made NOT NULL.

alter table meeting
    add column start_time timestamptz,
    add column end_time   timestamptz,
    add column status     varchar(255);

create table meeting_participant (
    id         bigint generated by default as identity primary key,
    meeting_id bigint not null references meeting (id),
    user_id    bigint not null references app_user (id),
    role       varchar(255),
    vote       varchar(255),
    constraint uk_meeting_participant_meeting_user unique (meeting_id, user_id)
);

create table slot_meeting (
    meeting_id bigint not null references meeting (id),
    slot_id    bigint not null references slot (id),
    primary key (meeting_id, slot_id)
);

insert into slot_meeting (meeting_id, slot_id)
select meeting_id, id from slot where meeting_id is not null;

alter table slot drop column meeting_id;
